language: c
compiler:
  - gcc
  - clang

# Requring sudo as a work around for https://github.com/travis-ci/travis-ci/issues/8082
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - autoconf-archive
      - dbus
      - dbus-x11
      - cmake
      - lcov
      - libglib2.0-dev
      - libdbus-1-dev
      - realpath
  coverity_scan:
    project:
      name: 01org/tpm2-abrmd
      description: Build submitted via Travis-CI
    notification_email: flihp@twobit.us
    build_command_prepend: "./configure; make clean"
    build_command: "make -j$(nproc)"
    branch_pattern: coverity_scan

env:
  global:
    # COVERITY_SCAN_TOKEN created by coverity using 'travis encrypt' using
    # project repo public key
    - secure: "hWep+zj8S3ahEGUpOaFbsHVqJ/1Gpf7+4Vos0Op1jyCF0Iw3r/MRxC1AABhxOjPhlNNf9q19b0IjVzVWh+owiFItK/NCgNG+daSuCk945F5tREYKFui+b9JrLMGx8+zfrL+KAy3BVDUUobLrh7vBTdbr9Wg4Kbryt6lBh0wpPnbMqCuUKEwAYw8K9YpoviqGdW1AWwWEpApoXtjukiF3Virc+sfRN/3xpDpHyc7LESzREE/xkZe879e1pFGLys7perOf2JhgKdj0B0otQXPcPuoB8ppFsxTQwbZbcfpZW/l7Vo6aUjmoXw6+DTZK+skne2K9uCP2gjuVwLnkzgBhX8OYVyHscmA+xl0wLIwkTkPcW76bfOVZPkgaKGdKBW7mdl2Tk8DBZfF10XZ0zSLAOEwUeYkIr4vc4ybGRcw9xS6ixXeENzW9BR1NUktSdQBrMSYnrRvDQkEKiUpd7f4uFOKQT0evvjvAI8rXEcC5eo8ODJYHni0Zep/c/rKEPduUsZgZQ18F86q/G3DtIl+69/gDEEUKnDXSFejFfzO+NGWp+jL5aybE0pjzXsiLmwklDiY6po+dgkiTbL3SKlMl8a+miteNu2fgar8D443afGiHABUpiRwNYN/47WombgYst5ZcnnDFmUIYa7SYoxZAeCsCTySdyTso02POFAKYz5U="
    # run coverity scan on gcc build to keep from DOSing coverity
    - coverity_scan_run_condition='"$CC" = gcc'
    - PREFIX=/usr
    - DEPS="${TRAVIS_BUILD_DIR}/deps"
    - DESTDIR="${TRAVIS_BUILD_DIR}/destdir"
    - ACLOCAL_PATH="${DESTDIR}${PREFIX}/share/aclocal:${ACLOCAL_PATH}"
    - PKG_CONFIG_PATH="${DESTDIR}${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"
    - LD_LIBRARY_PATH="${DESTDIR}${PREFIX}/lib:${LD_LIBRARY_PATH}"
    - CFLAGS="-I${DESTDIR}${PREFIX}/include"
    - CMOCKA_LIBS="-L${DESTDIR}${PREFIX}/lib -lcmocka"

install:
  - pip install --user cpp-coveralls
  - mkdir ${DESTDIR} ${DEPS} && pushd ${DEPS}
  - wget http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2017.09.28.tar.xz
  - sha256sum autoconf-archive-2017.09.28.tar.xz | grep -q 5c9fb5845b38b28982a3ef12836f76b35f46799ef4a2e46b48e2bd3c6182fa01
  - tar xJf autoconf-archive-2017.09.28.tar.xz && pushd autoconf-archive-2017.09.28
  - ./configure --prefix=${PREFIX} && make && make install
  - popd # autoconf-archive
  - wget https://cmocka.org/files/1.1/cmocka-1.1.1.tar.xz
  - tar -Jxvf cmocka-1.1.1.tar.xz
  - mkdir cmocka-1.1.1/build && pushd cmocka-1.1.1/build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_BUILD_TYPE=Release
  - make -j$(nproc) install
  - popd # cmocka
  - git clone -b 1.x --single-branch https://github.com/01org/tpm2-tss.git
  - pushd tpm2-tss
  - ./bootstrap
  - ./configure --prefix=${PREFIX}
  - make -j$(nproc) install
  - popd # tpm2-tss
  - wget https://downloads.sourceforge.net/project/ibmswtpm2/ibmtpm974.tar.gz
  - sha256sum ibmtpm974.tar.gz | grep -q ^8e45d86129a0adb95fee4cee51f4b1e5b2d81ed3e55af875df53f98f39eb7ad7
  - mkdir ibmtpm
  - tar axf ibmtpm974.tar.gz -C ibmtpm
  - make -C ibmtpm/src -j$(nproc)
  - popd # ${DEPS}

before_script:
  - ./bootstrap

script :
  - echo 'Configuring source code...' && echo -en 'travis_fold:start:tabrmd-configure\\r'
  - |
    CONFIGURE_OPTIONS="--enable-unit --with-simulatorbin=${DEPS}/ibmtpm/src/tpm_server"
    if [ "$CC" = "gcc" ]; then
        CONFIGURE_OPTIONS="$CONFIGURE_OPTIONS --enable-code-coverage"
    fi
    ./configure ${CONFIGURE_OPTIONS}
  - echo -en 'travis_fold:end:tabrmd-configure\\r'
  - echo "Running make 'distcheck' target..." && echo -en 'travis_fold:start:tabrmd-distcheck\\r'
  - dbus-launch make -j$(nproc) distcheck
  - echo -en 'travis_fold:end:tabrmd-distcheck\\r'
  - echo "Running make 'check-code-coverage' target..." && echo -en 'travis_fold:start:tabrmd-check-code-coverage\\r'
  - dbus-launch make -j$(nproc) check-code-coverage
  - |
    if [ \( "$CC" = "gcc" \) -a \( ! -z "$COVERALLS_REPO_TOKEN" \) ]; then
        echo "Uploading test coverage metrics to coveralls."
        coveralls --build-root=./ --exclude=${DEPS} --exclude=${DESTDIR} --exclude=./test --exclude=tpm2-abrmd-$(cat VERSION) --exclude=./coverity --exclude=./src/tabrmd-generated.c --exclude=./src/tabrmd-generated.h --gcov-options '\-lp'
    fi
  - echo -en 'travis_fold:end:tabrmd-check-code-coverage\\r'
  - echo 'Dumping unit test logs...' && echo -en 'travis_fold:start:tabrmd-unit-logs\\r'
  - |
    cat test-suite*.log
    for LOG in $(ls -1 test/*.log); do
        echo "${LOG}"
        cat ${LOG}
    done
  - echo -en 'travis_fold:end:tabrmd-unit-logs\\r'
