language: c
compiler:
  - gcc
  - clang

# Requring sudo as a work around for https://github.com/travis-ci/travis-ci/issues/8082
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - autoconf-archive
      - dbus
      - dbus-x11
      - doxygen
      - cmake
      - lcov
      - libglib2.0-dev
      - libdbus-1-dev
      - liburiparser-dev
      - realpath
  coverity_scan:
    project:
      name: 01org/tpm2-abrmd
      description: Build submitted via Travis-CI
    notification_email: flihp@twobit.us
    build_command_prepend: "./bootstrap && ./configure"
    build_command: "make --jobs=$(nproc)"
    branch_pattern: coverity_scan

env:
  global:
    # COVERITY_SCAN_TOKEN created by coverity using 'travis encrypt' using
    # project repo public key
    - secure: "obb9XbzVIj7P/wBKXG6GIRlGSXFcQhTvAa6LX8wU279wt3t0uGakofOmw5SpFX9wnxCu6xd3yHaiUqAuFotf5Bb/ROfeqZGdBFUVSwmxEohzrxPH3KbYhd3lzACUSMNYBVwu+WZhzPK3cQRf8KtQw7V9qNP5qV+RfgXizo+r04w6g2hP8xeYIrJ86PUtLjFrvtd/OxXhWWb7i+dTDSSmUvdYi18XSyvtz+7H2OXJLZSO7Ns2WUAplkwre1pCgv2sg0pkxHQjjeIYEcvYZskiKsyyXT2AXZFTNa7KN51/N4lpk/Hb7ffjFMM9T6/NZ1JVY3UVpGOGYH4TM49macyws9b0RiwGpzW2qe2EKoiXLOEYk5erW/PoIM8PiNcvAgvQaU25/cZSDQaEn/S9DTLkC8AJHVmqY9tp9XVmesCrBhpeAnyDTAfiZ1t05HiFOqw7ByP1LM49ysvQk1cdlt28AvB90t6rttGUP8CUtwnasHOVASlZ/No7xRGFHlLLmfKVrZc31jZS4RHxthn4MKATzqkylMZQMVA2/jasRcfYTXiUPGUfuaxZfofSTpJANrGWAMC43FWqKi3jPVJ2/TdqZ2r/wXkK23SiF9Lu9X4QOGuLnbAuQENddqb1A3e2PH+0NC6O0ThWq69BcWmrtbD2ev0UDivbG8OQ1ZsSDm9UqVA="
    # run coverity scan on gcc build to keep from DOSing coverity
    - coverity_scan_run_condition='"$CC" = gcc'
    - PREFIX=/usr
    - DEPS="${TRAVIS_BUILD_DIR}/deps"
    - DESTDIR="${TRAVIS_BUILD_DIR}/destdir"
    - ACLOCAL_PATH="${DESTDIR}${PREFIX}/share/aclocal:${ACLOCAL_PATH}"
    - PKG_CONFIG_PATH="${DESTDIR}${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}"
    - LD_LIBRARY_PATH="${DESTDIR}${PREFIX}/lib:${LD_LIBRARY_PATH}"
    - CFLAGS="-I${DESTDIR}${PREFIX}/include"
    - CMOCKA_LIBS="-L${DESTDIR}${PREFIX}/lib -lcmocka"
    - PATH="${DEPS}/ibmtpm/src:${PATH}"

install:
  - pip install --user cpp-coveralls
  - mkdir ${DESTDIR} ${DEPS} && pushd ${DEPS}
  - wget https://download.01.org/tpm2/autoconf-archive-2017.09.28.tar.xz
  - sha256sum autoconf-archive-2017.09.28.tar.xz | grep -q 5c9fb5845b38b28982a3ef12836f76b35f46799ef4a2e46b48e2bd3c6182fa01
  - tar xJf autoconf-archive-2017.09.28.tar.xz && pushd autoconf-archive-2017.09.28
  - ./configure --prefix=${PREFIX} && make && make install
  - popd # autoconf-archive
  - wget https://download.01.org/tpm2/cmocka-1.1.1.tar.xz
  - tar -Jxvf cmocka-1.1.1.tar.xz
  - mkdir cmocka-1.1.1/build && pushd cmocka-1.1.1/build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_BUILD_TYPE=Release
  - make -j$(nproc) install
  - popd # cmocka
  - git clone -b master --single-branch https://github.com/01org/tpm2-tss.git
  - pushd tpm2-tss
  - ./bootstrap
  - ./configure --prefix=${PREFIX} --disable-doxygen-doc --disable-tcti-device --disable-esapi
  - make -j$(nproc) install
  - popd # tpm2-tss
  - sed -i -e "s&\(\/usr\/lib\/lib.*\.la\)&${DESTDIR}\1&" ${DESTDIR}${PREFIX}/lib/*.la
  - wget https://download.01.org/tpm2/ibmtpm974.tar.gz
  - sha256sum ibmtpm974.tar.gz | grep -q ^8e45d86129a0adb95fee4cee51f4b1e5b2d81ed3e55af875df53f98f39eb7ad7
  - mkdir ibmtpm
  - tar axf ibmtpm974.tar.gz -C ibmtpm
  - make -C ibmtpm/src -j$(nproc)
  - popd # ${DEPS}

before_script:
  - ./bootstrap

script :
# short-circuit normal build if we've already done a coverity scan
  - |
    if [ "${COVERITY_SCAN_BRANCH}" == 1 ]; then
        echo "COVERITY_SCAN_BRANCH set, not running normal build."
        exit 0
    fi
  - |
    CONFIGURE_OPTIONS="--disable-dlclose --enable-unit --enable-integration"
    case "$CC" in
    clang*)
        # Use -D_REENTRANT kludge so -pthread test works with scan-build:
        scan-build ./configure CFLAGS="$CFLAGS -D_REENTRANT" $CONFIGURE_OPTIONS
        if [ $? -ne 0 ]; then exit 1; fi
        dbus-launch scan-build --status-bugs make -j$(nproc) distcheck
        if [ $? -ne 0 ]; then exit 1; fi
        # exit code from scan-build is 0 if no bugs are found, failed tests
        # will go undetected unless we manually parse the test log for:
        # '# FAIL:  0'
        TEST_LOG_DIR=$(find ./tpm2-abrmd-* -name '_build')
        if [ -d "${TEST_LOG_DIR}" ]; then exit 1; fi
        TEST_LOG=$(find ./tpm2-abrmd-*/_build -name 'test-suite.log')
        if [ -f "${TEST_LOG}" ]; then
            grep '^#[[:space:]]\+FAIL:[[:space:]]\+0$' ${TEST_LOG}
        fi
        ;;
    gcc)
        ./configure ${CONFIGURE_OPTIONS} --enable-code-coverage
        if [ $? -ne 0 ]; then exit 1; fi
        dbus-launch make -j$(nproc) check
        if [ $? -ne 0 ]; then exit 1; fi
        if [ ! -z "$COVERALLS_REPO_TOKEN" ]; then
          coveralls --build-root=./ --exclude=${DEPS} --exclude=${DESTDIR} --exclude=./test --exclude=tpm2-abrmd-$(cat VERSION) --exclude=./coverity --exclude=./src/tabrmd-generated.c --exclude=./src/tabrmd-generated.h --gcov-options '\-lp'
        fi
        ;;
    *)
        echo "unsupported compiler"
        exit 1
    esac

after_failure:
  - |
    TEST_ROOT=tpm2-abrmd-*/_build
    # newer versions of automake have distcheck output under a new directory
    if [ -d ${TEST_ROOT}/sub ]; then
        TEST_ROOT=${TEST_ROOT}/sub
    fi
    cat ${TEST_ROOT}/test-suite.log
    find ${TEST_ROOT}/test -name '*.log' | while read LOG; do
        echo "dumping test log: ${LOG}"
        cat ${LOG}
    done
